# Generated by Django 4.2 on 2024-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
