# Generated by Django 4.2 on 2024-03-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
    ]
