# Generated by Django 4.2 on 2024-03-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('profesor', 'Profesor')], default='normal', max_length=10),
        ),
    ]
